### ISSUE TITLE
No output after test run_pipeline_test.sh

### ISSUE THREAD

**Issue by nalandaatmi** [marbl/metAMOS#199] opened 2015-04-23 20:40 UTC
Hi Sergey/Treangen,

Installation process in section A) did not see any errors. Testing pipeline is section B), where it got terminated and displayed "Oops, MetAMOS finished with errors! see text in red above for details." But I could not see any red font text.

A) I am trying to install metAMOS pipeline in our cluster. Completed following commands
    1) python INSTALL.py core
    2) python INSTALL.py iMetAMOS
    3) python INSTALL.py core phylosift
    4) python INSTALL.py optional
    Below are the last ~25 lines after running these commands. I did not get any errors for the above commands.
***************************************************
matplotlib-1.1.0/CXX/Objects.hxx
matplotlib-1.1.0/CXX/cxx_extensions.cxx
mv: cannot move `./Utilities/python/matplotlib-1.1.0' to `./Utilities/python/matplotlib/matplotlib-1.1.0': File exists
Checking whether refseq_protein is complete. Expecting 18 partitions.

Run setup.py..
running install_scripts
running egg_info
writing metAMOS.egg-info/PKG-INFO
writing top-level names to metAMOS.egg-info/top_level.txt
writing dependency_links to metAMOS.egg-info/dependency_links.txt
reading manifest file 'metAMOS.egg-info/SOURCES.txt'
writing manifest file 'metAMOS.egg-info/SOURCES.txt'
running build_scripts
copying build/scripts-2.7/runPipeline.py -> /users/nalanda/metAMOS-1.5rc3
copying build/scripts-2.7/initPipeline.py -> /users/nalanda/metAMOS-1.5rc3
changing mode of /users/nalanda/metAMOS-1.5rc3/runPipeline.py to 755
changing mode of /users/nalanda/metAMOS-1.5rc3/initPipeline.py to 755
running build_ext
skipping './src/preprocess.c' Cython extension (up-to-date)
skipping './src/annotate.c' Cython extension (up-to-date)
skipping './src/fannotate.c' Cython extension (up-to-date)
skipping './src/mapreads.c' Cython extension (up-to-date)
skipping './src/findorfs.c' Cython extension (up-to-date)
skipping './src/findscforfs.c' Cython extension (up-to-date)
skipping './src/scaffold.c' Cython extension (up-to-date)
*************************************************

B) But when I execute ./run_pipeline_test.sh. I got the below error and test pipeline got terminated with an below message.However, I did not see any error messages in red font.

[nalanda@comp-0-12 Test]$ ./run_pipeline_test.sh 
Warning: BLASR is not found, some functionality will not be available
Warning: MetaGeneMark is not found, some functionality will not be available
Warning: REAPR is not found, some functionality will not be available
Project directory already exists, please specify another
Alternatively, use runPipeline to run an existing project
[Steps to be skipped]:  set(['FunctionalAnnotation', 'FindRepeats'])
Starting Task = runpipeline.RUNPIPELINE
Starting metAMOS pipeline
Warning: BLASR is not found, some functionality will not be available
Warning: MetaGeneMark is not found, some functionality will not be available
Warning: REAPR is not found, some functionality will not be available
[Available RAM: 839 GB]
	*ok
[Available CPUs: 80]
	*ok

________________________________________
Tasks which will be run:

Task = preprocess.Preprocess
Task = assemble.SplitAssemblers
Task = assemble.Assemble
Task = assemble.CheckAsmResults
Task = assemble.SplitMappers
Task = mapreads.MapReads
Task = mapreads.CheckMapResults
Task = mapreads.SplitForORFs
Task = findorfs.FindORFS
Task = validate.Validate
Task = findreps.FindRepeats
Task = annotate.Annotate
Task = fannotate.FunctionalAnnotation
Task = scaffold.Scaffold
Task = findscforfs.FindScaffoldORFS
Task = abundance.Abundance
Task = propagate.Propagate
Task = classify.Classify
Task = postprocess.Postprocess
________________________________________
Oops, MetAMOS finished with errors! see text in red above for details.
[nalanda@comp-0-12 Test]$

**Comment by skoren** [comment] 2015-04-24 13:40
Duplicate of #200.

**Closed by skoren** 2015-04-24 13:40 UTC
